# Generated by Django 4.2 on 2023-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('project_date', models.DateField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.CharField(max_length=150)),
                ('project_link', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tech_Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('stack_name', models.CharField(max_length=20)),
                ('stack_proficency', models.CharField(max_length=20)),
                ('stack_logo', models.CharField(max_length=500)),
            ],
        ),
    ]
