# Generated by Django 4.2 on 2023-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_project_date_projects_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech_stacks',
            old_name='stack_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='tech_stacks',
            old_name='stack_name',
            new_name='proficency',
        ),
        migrations.RemoveField(
            model_name='tech_stacks',
            name='stack_proficency',
        ),
        migrations.AddField(
            model_name='tech_stacks',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
