# Generated by Django 4.2 on 2023-05-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_stack_logo_tech_stacks_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='source',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
