# Generated by Django 4.2 on 2023-05-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_skills_delete_tech_stacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='proficency',
            new_name='proficiency',
        ),
    ]
